"""remove ass table

Revision ID: 473a1f9be204
Revises: a9753c16198a
Create Date: 2018-12-17 19:28:06.895115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473a1f9be204'
down_revision = 'a9753c16198a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bus_reviews')
    op.drop_constraint('resList_id_key', 'resList', type_='unique')
    op.alter_column('reviews', 'business_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('reviews_id_key', 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reviews_id_key', 'reviews', ['id'])
    op.alter_column('reviews', 'business_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint('resList_id_key', 'resList', ['id'])
    op.create_table('bus_reviews',
    sa.Column('business_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name='bus_reviews_business_id_fkey'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='bus_reviews_review_id_fkey')
    )
    # ### end Alembic commands ###
