"""migration 1

Revision ID: a9753c16198a
Revises: 
Create Date: 2018-12-13 20:15:54.456715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9753c16198a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'resList', ['id'])
    op.create_unique_constraint(None, 'reviews', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_constraint(None, 'resList', type_='unique')
    # ### end Alembic commands ###
